# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: La Buena Cuchara
email: labuenacucharacr@gmail.com
author: Sophia Rodriguez
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    icon: facebook
    url: https://www.facebook.com/labuenacuchara
  - title: twitter
    icon: twitter
    url: https://twitter.com/
  - title: email
    icon: envelope
    url: mailto:labuenacucharacr@gmail.com